package:
  name: condatest
  version: "1.5"

source:
#  git_url: https://github.com/MarkusFraKS/condatest.git
  path: .

#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools

  host:
    - python
    - numpy x.x

  run:
    - python
    - numpy x.x

about:
  doc_url: file://./doc/docs.html
#test:
#  imports:
#    - main
