package:
  name: condatest
  version: "1.7"

source:
  git_url: https://github.com/MarkusFraKS/condatest.git
  git_rev: 1.7
#  path: .

#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools

  host:
    - python ">=3.6"
    - numpy x.x

  run:
    - python ">=3.6"
    - numpy x.x

about:
  doc_url: file://./doc/docs.html
#test:
#  imports:
#    - main
