package:
  name: condatest
  version: {{GIT_DESCRIBE_TAG | replace("v", "")}}

source:
  git_url: https://github.com/MarkusFraKS/condatest.git
  git_rev: "v2.0"
#  path: .

build:
  number: 2
#  noarch: python
#  string: np{{ numpy | replace(".", "") }}py{{ python | replace(".", "") }}
#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools

  host:
    - python
    - numpy x.x

  run:
    - python
    - numpy x.x

about:
  doc_url: file://./doc/docs.html

test:
  imports:
    - condatest
