{% set setuppy = load_setup_py_data() %}

package:
  name: condatest
#  version: {{GIT_DESCRIBE_TAG | replace("v", "")}}
#  version: "2.5"
  version: {{ setuppy.get('version') }}
source:
#  git_url: https://github.com/MarkusFraKS/condatest.git
#  git_rev: "v2.3"
  path: .

build:
  number: 1
#  noarch: python
#  string: np{{ numpy | replace(".", "") }}py{{ python | replace(".", "") }}
#build:
#  script: python setup.py install

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools

  host:
    - python {{ python }}
    - numpy {{ numpy }}

  run:
    - python {{ python }}
    - numpy {{ numpy }}

about:
  home: https://github.com/MarkusFraKS/condatest.git
  license: MIT
  license_file: LICENSE
  doc_url: /doc/docs.html

test:
  imports:
    - condatest


