package:
  name: condatest
  version: {{GIT_DESCRIBE_TAG}}

source:
  git_url: https://github.com/MarkusFraKS/condatest.git
  git_rev: "v1.8"
#  path: .

build:
  noarch: python

#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python {{python}}

  host:
    - python
    - numpy >=1.17

  run:
    - python
    - numpy >=1.17

about:
  doc_url: file://./doc/docs.html
#test:
#  imports:
#    - main
